// <auto-generated />
using ConsoleApp.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace ConsoleApp.SQLite.Migrations
{
    [DbContext(typeof(AccessDb))]
    [Migration("20171002010359_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ConsoleApp.SQLite.Password", b =>
                {
                    b.Property<int>("PasswordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EncryptedPassword");

                    b.Property<string>("Key");

                    b.Property<int>("TagForeignKey");

                    b.Property<int>("UserNameForeignKey");

                    b.HasKey("PasswordId");

                    b.ToTable("Passwords");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("PasswordForeignKey");

                    b.Property<int>("UserNameForeignKey");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.UserName", b =>
                {
                    b.Property<int>("UserNameId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("UserPasswordForeignKey");

                    b.HasKey("UserNameId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.UserPassword", b =>
                {
                    b.Property<int>("UserPasswordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Salt");

                    b.Property<string>("SaltAndHash");

                    b.Property<int>("UserNameForeignKey");

                    b.HasKey("UserPasswordId");

                    b.ToTable("UsersPasswords");
                });
#pragma warning restore 612, 618
        }
    }
}
